### ISSUE TITLE
Can't run pppoe-simulator.py

### ISSUE THREAD

**Issue by nativeego** [impulse/ac2100-openwrt-guide#10]
Hi,

When I run the script pppoe-simulator.py, i have got an error as it show below. i enter the correct MAC (from the bottom of the router). Is anyone else handle this issue? any assist will we welcome. thanks.

sudo python3 pppoe-simulator.py
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
Traceback (most recent call last):
  File "pppoe-simulator.py", line 181, in <module>
    mac_server = get_if_hwaddr(interface)
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 55, in get_if_hwaddr
    mac = get_if_raw_hwaddr(iff)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 84, in get_if_raw_hwaddr
    return struct.unpack("16xh6s8x",get_if(iff,SIOCGIFHWADDR))[1]
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 288, in get_if
    ifreq = ioctl(s, cmd, struct.pack("16s16x",bytes(iff,'utf-8')))
OSError: [Errno 19] No such device

**Comment by nativeego** [comment]
I needed to change the default interface in pppoe-simulator.py : line 5 (under the comment: # In most cases you just have to change this:)
