### ISSUE TITLE
name 'PPPoED_Tags' is not defined

### ISSUE THREAD

**Issue by nativeego** [impulse/ac2100-openwrt-guide#11]
Hi, Did someone handled that issue? thanks

root@nati-VirtualBox:/home/nati/ac2100-openwrt-guide-master# sudo python3 pppoe-simulator.py
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
Waiting for packets
Traceback (most recent call last):
  File "pppoe-simulator.py", line 183, in <module>
    sniff(prn=packet_callback, filter="pppoed or pppoes", lfilter=isNotOutgoing)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 603, in sniff
    r = prn(p)
  File "pppoe-simulator.py", line 63, in packet_callback
    for tag in pkt[PPPoED][PPPoED_Tags].tag_list:
NameError: name 'PPPoED_Tags' is not defined

**Comment by nativeego** [comment]
I didn't install well both :

sudo apt install python3-scapy
pip3 install netcat
