### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by maateoab** [impulse/ac2100-openwrt-guide#12]
Waiting for packets
Client->Server   |   Discovery Initiation
Server->Client   |   Discovery Offer
Traceback (most recent call last):
  File "pppoe-simulator.py", line 183, in <module>
    sniff(prn=packet_callback, filter="pppoed or pppoes", lfilter=isNotOutgoing)
  File "/usr/lib/python3.8/site-packages/scapy/sendrecv.py", line 1036, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/scapy/sendrecv.py", line 989, in _run
    session.on_packet_received(p)
  File "/usr/lib/python3.8/site-packages/scapy/sessions.py", line 82, in on_packet_received
    result = self.prn(pkt)
  File "pppoe-simulator.py", line 68, in packet_callback
    sendp(eth_discovery /
  File "/usr/lib/python3.8/site-packages/scapy/sendrecv.py", line 377, in sendp
    results = __gen_send(socket, x, inter=inter, loop=loop,
  File "/usr/lib/python3.8/site-packages/scapy/sendrecv.py", line 308, in __gen_send
    s.send(p)
  File "/usr/lib/python3.8/site-packages/scapy/arch/linux.py", line 476, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python3.8/site-packages/scapy/supersocket.py", line 71, in send
    sx = raw(x)
  File "/usr/lib/python3.8/site-packages/scapy/compat.py", line 53, in raw
    return bytes(x)
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 498, in __bytes__
    return self.build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 618, in build
    p = self.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 603, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 590, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 600, in do_build
    pkt = self.self_build()
  File "/usr/lib/python3.8/site-packages/scapy/packet.py", line 581, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python3.8/site-packages/scapy/fields.py", line 151, in addfield
    return s + self.struct.pack(self.i2m(pkt, val))
  File "/usr/lib/python3.8/site-packages/scapy/fields.py", line 1531, in i2m
    f = fld.i2len(pkt, fval)
  File "/usr/lib/python3.8/site-packages/scapy/fields.py", line 1020, in i2len
    return len(x)
TypeError: object of type 'NoneType' has no len()

**Comment by nativeego** [comment]
I think you are handling the same issue as reported here: (there is a solution for that issue in the link below)
https://github.com/impulse/ac2100-openwrt-guide/issues/7
