### ISSUE TITLE
Error in PPPoE-Simulator.py - NameError: name 'PPPoED_Tags' is not defined

### ISSUE THREAD

**Issue by v17564** [impulse/ac2100-openwrt-guide#13]
Hello.

My system is MX Linux 19.3 of 32 bits.

Python 3 data:

> Python 3.7.3
> python3-scapy  (2.4.0-2).

I found the next error:
```
# python3 PPPoE-Simulator.py 
Waiting for packets
Traceback (most recent call last):
  File "PPPoE-Simulator.py", line 183, in <module>
    sniff(prn=packet_callback, filter="pppoed or pppoes", lfilter=isNotOutgoing)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 780, in sniff
    r = prn(p)
  File "PPPoE-Simulator.py", line 63, in packet_callback
    for tag in pkt[PPPoED][PPPoED_Tags].tag_list:
NameError: name 'PPPoED_Tags' is not defined
```
I need help for resolve it, didn't found a solution searching in internet.
Thanks.

**Comment by v17564** [comment]
Hello.

I already found the solution to the problem, my scapy/ppp.py has not defined the variables PPPoED_Tags and PPPoED_Tag. Searching online I found that it's need the minimum version of scapy 2.4.2.

Rereading the manual I have seen it put (Ubuntu), so quoted without further clarification. **I think maybe it would be advisable to clarify that it is essential to use Ubuntu - Xubuntu 20.04 LTS (at least), since it installs versions of Python 3.8.5 and Python3-scapy 2.4.3-4**, with which Python programs work at first.

I installed Xubuntu 20.04 LTS on a Virtualbox machine. I proceeded to install Python and Scapy and then changed the configuration of the virtualbox network card to bridge mode, set the IP parameters in the virtual machine and the Python programs worked to the first one and so I could install Openwrt without problems.

Thanks.
